### ISSUE TITLE
Deprecated function

### ISSUE THREAD

**Issue by robert1112** [YotpoLtd/woocommerce-plugin#18]
Hi 

I got the errors on debug mode. Thank you.

```
Deprecated: Non-static method WooCommerce::plugin_path() should not be called statically in /var/www/blog/wp-content/plugins/yotpo-social-reviews-for-woocommerce/wc_yotpo.php on line 141

Deprecated: Non-static method WooCommerce::plugin_path() should not be called statically in /var/www/blog/wp-content/plugins/yotpo-social-reviews-for-woocommerce/wc_yotpo.php on line 145
```

System info:
```
WC version:		3.3.5
WP version:		4.9.4
Server info:		nginx/1.13.12
PHP version:		7.1.16
```

**Comment by hxii** [comment]
@robert1112 Addressed here: https://github.com/hxii/woocommerce-plugin/tree/hxii-deprecated-method

**Comment by robert1112** [comment]
@hxii Hi The rating stars didnt show up on shop or single product page after installing the new plugin and fill up the tokens. Does it work fine with you? Thanks.

**Comment by hxii** [comment]
@robert1112 Everything works fine for me. This could perhaps be a hooking issue?
Have you seen any errors?

**Comment by hxii** [comment]
@robert1112 Yes, or any of the PHP error logs.

**Comment by robert1112** [comment]
@hxii  Thanks I will check them first. Thank you so much.
