### ISSUE TITLE
Use WooCommerce 3.x CRUD classes compatibility

### ISSUE THREAD

**Issue by pawelkmpt** [YotpoLtd/woocommerce-plugin#5]
Hello! WooCommerce 3.0 introduced CRUD classes and now, the right way to access properties is to use getters. Your plugin uses old approach with direct properties access and it generates solid amount of notices in log.

Do you plan any update to keep compatibility with WooCommerce?

- [ ]  `get_product is deprecated since version 3.0! Use wc_get_product instead. wc_yotpo.php:152`
- [ ]  `post was called incorrectly. Product properties should not be accessed directly. Please see Debugging in WordPress for more information. (This message was added in version 3.0.) wc_yotpo.php:153`
- [ ]  `id was called incorrectly. Product properties should not be accessed directly. Please see Debugging in WordPress for more information. (This message was added in version 3.0.) wc_yotpo.php:170`
- [ ]  `WC_Product::get_post_data is deprecated since version 3.0! Use get_post instead. wc_yotpo.php:180`

**Comment by demlaip** [comment]
this might be possible reason, which lead to no yotpo widgets loading over woocommerce based site

**Comment by twittem** [comment]
This definitely something that needs to be updated. These functions have now been depreciated for 304 days, and with the cost of the tool... Compatibility should be a top priority.

**Comment by SlavicB** [comment]
Hi Edward, we will look into it.

**Comment by billykov** [comment]
We will include an update for those functions on version 1.1.8 which supposed to be released on Q2.
We have to keep in mind that updating them would break support for any WooCommerce version below 3.0

**Comment by pawelkmpt** [comment]
@billykov you don't have to break compatibility with older versions of WooCommerce. Just look at the examples of other plugins and compare versions using `WC_VERSION` and `version_compare()`
